In [43]:
import pandas as pd

In [44]:
df = pd.read_csv('data/data.csv', index_col=0)
df

       CO(mg/m^3)  People  Suction Pump
0        0.075034     0.0      0.000000
1        0.003099     0.0      0.000000
2        0.022322     0.0      0.000000
3        0.066063     0.0      0.000000
4        0.074102     0.0      0.000000
...           ...     ...           ...
10328    3.023261     6.0      0.247546
10329    2.323334     4.0      0.319441
10330    2.313576     2.0      0.360099
10331    1.992810     3.0      0.510426
10332    1.984202     1.0      0.980899

[10333 rows x 3 columns]

In [45]:
# for every column except the first two, create the shift of 1 to 6
for col in df.columns[:]:
    for i in range(1, 7):
        if col in list(df.columns[1:]):
            df[f'{col}_lag_{i}'] = df[col].shift(-i)
        #if col in list(df.columns[:]):
        df[f'{col}_prev_{i}'] = df[col].shift(i)

for col in df.columns[:1]:
    for i in range(1, 7):
        df[f'{col}_lag_{i}'] = df[col].shift(-i)
df.dropna(inplace=True)
df

,CO(mg/m^3),People,Suction Pump,CO(mg/m^3)_prev_1,CO(mg/m^3)_prev_2,CO(mg/m^3)_prev_3,CO(mg/m^3)_prev_4,CO(mg/m^3)_prev_5,CO(mg/m^3)_prev_6,People_lag_1,...,Suction Pump_lag_5,Suction Pump_prev_5,Suction Pump_lag_6,Suction Pump_prev_6,CO(mg/m^3)_lag_1,CO(mg/m^3)_lag_2,CO(mg/m^3)_lag_3,CO(mg/m^3)_lag_4,CO(mg/m^3)_lag_5,CO(mg/m^3)_lag_6
6,0.012148,0.0,0.000000,0.050855,0.074102,0.066063,0.022322,0.003099,0.075034,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.011440,0.036073,0.000000,0.131717,0.060999
7,0.000000,0.0,0.000000,0.012148,0.050855,0.074102,0.066063,0.022322,0.003099,0.0,...,0.000000,0.000000,0.000000,0.000000,0.011440,0.036073,0.000000,0.131717,0.060999,0.112400
8,0.011440,0.0,0.000000,0.000000,0.012148,0.050855,0.074102,0.066063,0.022322,0.0,...,0.000000,0.000000,0.000000,0.000000,0.036073,0.000000,0.131717,0.060999,0.112400,0.085512
9,0.036073,0.0,0.000000,0.011440,0.000000,0.012148,0.050855,0.074102,0.066063,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.131717,0.060999,0.112400,0.085512,0.038520
10,0.000000,0.0,0.000000,0.036073,0.011440,0.000000,0.012148,0.050855,0.074102,0.0,...,0.000000,0.000000,0.000000,0.000000,0.131717,0.060999,0.112400,0.085512,0.038520,0.027682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10322,0.406784,0.0,0.960347,0.364646,0.463441,0.571493,0.878059,1.178551,1.583330,0.0,...,0.869826,0.178742,0.247546,0.104190,0.450000,1.006211,3.906030,4.891611,3.560768,3.023261
10323,0.450000,0.0,1.000000,0.406784,0.364646,0.463441,0.571493,0.878059,1.178551,0.0,...,0.247546,0.243785,0.319441,0.178742,1.006211,3.906030,4.891611,3.560768,3.023261,2.323334
10324,1.006211,0.0,0.852625,0.450000,0.406784,0.364646,0.463441,0.571493,0.878059,0.0,...,0.319441,0.475112,0.360099,0.243785,3.906030,4.891611,3.560768,3.023261,2.323334,2.313576
10325,3.906030,0.0,0.234926,1.006211,0.450000,0.406784,0.364646,0.463441,0.571493,9.0,...,0.360099,0.731181,0.510426,0.475112,4.891611,3.560768,3.023261,2.323334,2.313576,1.992810
10326,4.891611,9.0,0.216778,3.906030,1.006211,0.450000,0.406784,0.364646,0.463441,10.0,...,0.510426,0.883850,0.980899,0.731181,3.560768,3.023261,2.323334,2.313576,1.992810,1.984202

In [46]:
list(df.columns)

['CO(mg/m^3)',
 'People',
 'Suction Pump',
 'CO(mg/m^3)_prev_1',
 'CO(mg/m^3)_prev_2',
 'CO(mg/m^3)_prev_3',
 'CO(mg/m^3)_prev_4',
 'CO(mg/m^3)_prev_5',
 'CO(mg/m^3)_prev_6',
 'People_lag_1',
 'People_prev_1',
 'People_lag_2',
 'People_prev_2',
 'People_lag_3',
 'People_prev_3',
 'People_lag_4',
 'People_prev_4',
 'People_lag_5',
 'People_prev_5',
 'People_lag_6',
 'People_prev_6',
 'Suction Pump_lag_1',
 'Suction Pump_prev_1',
 'Suction Pump_lag_2',
 'Suction Pump_prev_2',
 'Suction Pump_lag_3',
 'Suction Pump_prev_3',
 'Suction Pump_lag_4',
 'Suction Pump_prev_4',
 'Suction Pump_lag_5',
 'Suction Pump_prev_5',
 'Suction Pump_lag_6',
 'Suction Pump_prev_6',
 'CO(mg/m^3)_lag_1',
 'CO(mg/m^3)_lag_2',
 'CO(mg/m^3)_lag_3',
 'CO(mg/m^3)_lag_4',
 'CO(mg/m^3)_lag_5',
 'CO(mg/m^3)_lag_6']

In [47]:
df.to_csv('data/data_lagged.csv')